-- stg_rextag_unitedstates_natural_gas_GasProcessingPlants.sql
-- Auto-generated by rextag scan. Edit column renames in _sources.yml meta.rename.

{{
    config(
        materialized='view',
    )
}}

select * from {{ source('rextag_unitedstates_natural_gas', 'GasProcessingPlants') }}
