-- stg_rextag_unitedstates_power_and_renewables_EnergyCommunities_CoalClosure.sql
-- Auto-generated by rextag scan. Edit column renames in _sources.yml meta.rename.

{{
    config(
        materialized='view',
    )
}}

select * from {{ source('rextag_unitedstates_power_and_renewables', 'EnergyCommunities_CoalClosure') }}
