-- stg_common_cultural_Counties.sql
-- Auto-generated by rextag scan. Edit column renames in _sources.yml meta.rename.

{{
    config(
        materialized='view',
    )
}}

select * from {{ source('common_cultural', 'Counties') }}
