-- stg_floodhazard_FloodHazard.sql
-- Auto-generated by rextag scan. Edit column renames in _sources.yml meta.rename.

{{
    config(
        materialized='view',
    )
}}

select * from {{ source('floodhazard', 'FloodHazard') }}
