-- stg_rextag_financial_StockExchangeTickerSymbols.sql
-- Auto-generated by rextag scan. Edit column renames in _sources.yml meta.rename.

{{
    config(
        materialized='view',
    )
}}

select * from {{ source('rextag_financial', 'StockExchangeTickerSymbols') }}
