-- stg_rextag_financial_Financial_2016Q1.sql
-- Auto-generated by rextag scan. Edit column renames in _sources.yml meta.rename.

{{
    config(
        materialized='view',
    )
}}

select * from {{ source('rextag_financial', 'Financial_2016Q1') }}
