-- stg_rextag_unitedstates_common_energy_Fields.sql
-- Auto-generated by rextag scan. Edit column renames in _sources.yml meta.rename.

{{
    config(
        materialized='view',
    )
}}

select * from {{ source('rextag_unitedstates_common_energy', 'Fields') }}
